version: '3.8'

services:
  php:
    build: .
    container_name: lab9_php
    volumes:
      - ./:/var/www/html 
    environment:
      - DB_HOST=db
      - DB_NAME=test_db
    depends_on:
      - db
    networks:
      - taxi_network

  db:
    image: mysql:8.0
    container_name: lab9_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    networks:
      - taxi_network

  web:
    image: nginx:1.27-alpine
    container_name: lab9_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html                       
      - ./nginx:/etc/nginx/conf.d              
    depends_on:
      - php
    networks:
      - taxi_network

networks:
  taxi_network:
    driver: bridge
